from enum import Enum

__NAMESPACE__ = "http://www.vdv.de/ojp"


class AccessibilityFeatureTypesEnumeration(Enum):
    """
    Allowed values for AccessibilityFeature (for mobility and sensory
    impairments, assistance and important elements to pay attention to).
    """
    LOW_FLOOR_ACCESS = "lowFloorAccess"
    STEP_FREE_ACCESS = "stepFreeAccess"
    ACCESS_WITH_STEPS = "accessWithSteps"
    SLIDING_STEP = "slidingStep"
    RAISED_KERB = "raisedKerb"
    NARROW_ENTRANCE = "narrowEntrance"
    WHEELCHAIR_LIFT = "wheelchairLift"
    MANUAL_RAMP = "manualRamp"
    AUTOMATIC_RAMP = "automaticRamp"
    SUITABLE_FOR_WHEELCHAIRS = "suitableForWheelchairs"
    SUITABLE_FOR_UNASSISTED_WHEELCHAIRS = "suitableForUnassistedWheelchairs"
    SUITABLE_FOR_HEAVILIY_DISABLED = "suitableForHeaviliyDisabled"
    SUITABLE_FOR_PUSHCHAIRS = "suitableForPushchairs"
    SUITABLE_FOR_BICYCLES = "suitableForBicycles"
    TACTILE_PLATFORM_EDGES = "tactilePlatformEdges"
    TACTILE_GUIDING_STRIPS = "tactileGuidingStrips"
    TACTILE_OR_AUDITORY_SIGNS = "tactileOrAuditorySigns"
    VISUAL_SIGNS = "visualSigns"
    ELEVATOR_WITH_TACTILE_BUTTONS = "elevatorWithTactileButtons"
    ELEVATOR_WITH_ACOUSTIC_ANNOUNCEMENTS = "elevatorWithAcousticAnnouncements"
    AUDIO_INFORMATION = "audioInformation"
    AUDIO_FOR_HEARING_IMPAIRED = "audioForHearingImpaired"
    VISUAL_DISPLAYS = "visualDisplays"
    DISPLAYS_FOR_VISUALLY_IMPAIRED = "displaysForVisuallyImpaired"
    LARGE_PRINT_TIMETABLES = "largePrintTimetables"
    BOARDING_ASSISTANCE = "boardingAssistance"
    ONBOARD_ASSISTANCE = "onboardAssistance"
    UNACCOMPANIED_MINOR_ASSISTANCE = "unaccompaniedMinorAssistance"
    BARRIER = "barrier"
    VALIDATOR = "validator"
