from enum import Enum

__NAMESPACE__ = "http://datex2.eu/schema/2_0RC1/2_0"


class AccidentTypeEnum(Enum):
    ACCIDENT = "accident"
    ACCIDENT_INVOLVING_BICYCLES = "accidentInvolvingBicycles"
    ACCIDENT_INVOLVING_BUSES = "accidentInvolvingBuses"
    ACCIDENT_INVOLVING_HAZARDOUS_MATERIALS = "accidentInvolvingHazardousMaterials"
    ACCIDENT_INVOLVING_HEAVY_LORRIES = "accidentInvolvingHeavyLorries"
    ACCIDENT_INVOLVING_MASS_TRANSIT_VEHICLE = "accidentInvolvingMassTransitVehicle"
    ACCIDENT_INVOLVING_MOPEDS = "accidentInvolvingMopeds"
    ACCIDENT_INVOLVING_MOTORCYCLES = "accidentInvolvingMotorcycles"
    ACCIDENT_INVOLVING_RADIOACTIVE_MATERIAL = "accidentInvolvingRadioactiveMaterial"
    ACCIDENT_INVOLVING_TRAIN = "accidentInvolvingTrain"
    CHEMICAL_SPILLAGE_ACCIDENT = "chemicalSpillageAccident"
    COLLISION = "collision"
    COLLISION_WITH_ANIMAL = "collisionWithAnimal"
    COLLISION_WITH_OBSTRUCTION = "collisionWithObstruction"
    COLLISION_WITH_PERSON = "collisionWithPerson"
    EARLIER_ACCIDENT = "earlierAccident"
    FUEL_SPILLAGE_ACCIDENT = "fuelSpillageAccident"
    HEAD_ON_COLLISION = "headOnCollision"
    HEAD_ON_OR_SIDE_COLLISION = "headOnOrSideCollision"
    JACKKNIFED_ARTICULATED_LORRY = "jackknifedArticulatedLorry"
    JACKKNIFED_CARAVAN = "jackknifedCaravan"
    JACKKNIFED_TRAILER = "jackknifedTrailer"
    MULTIPLE_VEHICLE_COLLISION = "multipleVehicleCollision"
    MULTIVEHICLE_ACCIDENT = "multivehicleAccident"
    OIL_SPILLAGE_ACCIDENT = "oilSpillageAccident"
    OVERTURNED_HEAVY_LORRY = "overturnedHeavyLorry"
    OVERTURNED_TRAILER = "overturnedTrailer"
    OVERTURNED_VEHICLE = "overturnedVehicle"
    REAR_COLLISION = "rearCollision"
    SECONDARY_ACCIDENT = "secondaryAccident"
    SERIOUS_ACCIDENT = "seriousAccident"
    SIDE_COLLISION = "sideCollision"
    VEHICLE_OFF_ROAD = "vehicleOffRoad"
    VEHICLE_SPUN_AROUND = "vehicleSpunAround"
    OTHER = "other"
