from enum import Enum

__NAMESPACE__ = "http://www.siri.org.uk/siri"


class AirSubmodesOfTransportEnumeration(Enum):
    """
    Values for Air ModesOfTransport: TPEG pti_table_08.
    """
    PTI8_0 = "pti8_0"
    LOC15_0 = "loc15_0"
    UNKNOWN = "unknown"
    PTI8_1 = "pti8_1"
    LOC15_2 = "loc15_2"
    INTERNATIONAL_FLIGHT = "internationalFlight"
    PTI8_2 = "pti8_2"
    DOMESTIC_FLIGHT = "domesticFlight"
    PTI8_3 = "pti8_3"
    LOC15_1 = "loc15_1"
    INTERCONTINENTAL_FLIGHT = "intercontinentalFlight"
    PTI8_4 = "pti8_4"
    LOC15_4 = "loc15_4"
    DOMESTIC_SCHEDULED_FLIGHT = "domesticScheduledFlight"
    PTI8_5 = "pti8_5"
    LOC15_9 = "loc15_9"
    SHUTTLE_FLIGHT = "shuttleFlight"
    PTI8_6 = "pti8_6"
    LOC15_5 = "loc15_5"
    INTERCONTINENTAL_CHARTER_FLIGHT = "intercontinentalCharterFlight"
    PTI8_7 = "pti8_7"
    LOC15_6 = "loc15_6"
    INTERNATIONAL_CHARTER_FLIGHT = "internationalCharterFlight"
    PTI8_8 = "pti8_8"
    ROUND_TRIP_CHARTER_FLIGHT = "roundTripCharterFlight"
    PTI8_9 = "pti8_9"
    LOC15_8 = "loc15_8"
    SIGHTSEEING_FLIGHT = "sightseeingFlight"
    PTI8_10 = "pti8_10"
    LOC15_10 = "loc15_10"
    HELICOPTER_SERVICE = "helicopterService"
    PTI8_11 = "pti8_11"
    LOC15_7 = "loc15_7"
    DOMESTIC_CHARTER_FLIGHT = "domesticCharterFlight"
    PTI8_12 = "pti8_12"
    SCHENGEN_AREA_FLIGHT = "SchengenAreaFlight"
    PTI8_13 = "pti8_13"
    AIRSHIP_SERVICE = "airshipService"
    PTI8_14 = "pti8_14"
    ALL_AIR_SERVICES = "allAirServices"
    LOC14_3 = "loc14_3"
    SHORT_HAUL_INTERNATIONAL_FLIGHT = "shortHaulInternationalFlight"
    PTI8_255 = "pti8_255"
    LOC15_255 = "loc15_255"
    UNDEFINED_AIRCRAFT_SERVICE = "undefinedAircraftService"
