from enum import Enum

__NAMESPACE__ = "http://datex2.eu/schema/2_0RC1/2_0"


class DatexPictogramEnum(Enum):
    ADVISORY_SPEED = "advisorySpeed"
    BLANK_VOID = "blankVoid"
    CHAINS_OR_SNOW_TYRES_RECOMMENDED = "chainsOrSnowTyresRecommended"
    CROSS_WIND = "crossWind"
    DRIVING_OF_VEHICLES_LESS_THAN_XMETRES_APART_PROHIBITED = "drivingOfVehiclesLessThanXMetresApartProhibited"
    END_OF_ADVISORY_SPEED = "endOfAdvisorySpeed"
    END_OF_PROHIBITION_OF_OVERTAKING = "endOfProhibitionOfOvertaking"
    END_OF_PROHIBITION_OF_OVERTAKING_FOR_GOODS_VEHICLES = "endOfProhibitionOfOvertakingForGoodsVehicles"
    END_OF_SPEED_LIMIT = "endOfSpeedLimit"
    EXIT_CLOSED = "exitClosed"
    FOG = "fog"
    KEEP_ASAFE_DISTANCE = "keepASafeDistance"
    MAXIMUM_SPEED_LIMIT = "maximumSpeedLimit"
    NO_ENTRY = "noEntry"
    NO_ENTRY_FOR_GOODS_VEHICLES = "noEntryForGoodsVehicles"
    NO_ENTRY_FOR_VEHICLES_EXCEEDING_XTONNES_LADEN_MASS = "noEntryForVehiclesExceedingXTonnesLadenMass"
    NO_ENTRY_FOR_VEHICLES_HAVING_AMASS_EXCEEDING_XTONNES_ON_ONE_AXLE = "noEntryForVehiclesHavingAMassExceedingXTonnesOnOneAxle"
    NO_ENTRY_FOR_VEHICLES_HAVING_AN_OVERALL_HEIGHT_EXCEEDING_XMETRES = "noEntryForVehiclesHavingAnOverallHeightExceedingXMetres"
    NO_ENTRY_FOR_VEHICLES_HAVING_AN_OVERALL_LENGTH_EXCEEDING_XMETRES = "noEntryForVehiclesHavingAnOverallLengthExceedingXMetres"
    NO_ENTRY_FOR_VEHICLES_CARRYING_DANGEROUS_GOODS = "noEntryForVehiclesCarryingDangerousGoods"
    OTHER_DANGER = "otherDanger"
    OVERTAKING_BY_GOODS_VEHICLES_PROHIBITED = "overtakingByGoodsVehiclesProhibited"
    OVERTAKING_PROHIBITED = "overtakingProhibited"
    ROAD_CLOSED_AHEAD = "roadClosedAhead"
    ROADWORKS = "roadworks"
    SLIPPERY_ROAD = "slipperyRoad"
    SNOW = "snow"
    SNOW_TYRES_COMPULSORY = "snowTyresCompulsory"
    TRAFFIC_CONGESTION = "trafficCongestion"
