from enum import Enum

__NAMESPACE__ = "http://www.siri.org.uk/siri"


class RailSubmodesOfTransportEnumeration(Enum):
    """
    Values for Rail ModesOfTransport: TPEG pti_table_02, train link loc_table_13.
    """
    PTI2_0 = "pti2_0"
    LOC13_0 = "loc13_0"
    UNKNOWN = "unknown"
    PTI2_1 = "pti2_1"
    HIGH_SPEED_RAIL_SERVICE = "highSpeedRailService"
    PTI2_2 = "pti2_2"
    LOC13_3 = "loc13_3"
    LONG_DISTANCE_TRAIN = "longDistanceTrain"
    PTI2_3 = "pti2_3"
    LOC13_2 = "loc13_2"
    INTER_REGIONAL_RAIL_SERVICE = "interRegionalRailService"
    PTI2_4 = "pti2_4"
    CAR_TRANSPORT_RAIL_SERVICE = "carTransportRailService"
    PTI2_5 = "pti2_5"
    SLEEPER_RAIL_SERVICE = "sleeperRailService"
    PTI2_6 = "pti2_6"
    LOC13_4 = "loc13_4"
    REGIONAL_RAIL = "regionalRail"
    PTI2_7 = "pti2_7"
    LOC13_7 = "loc13_7"
    TOURIST_RAILWAY = "touristRailway"
    PTI2_8 = "pti2_8"
    RAIL_SHUTTLE = "railShuttle"
    PTI2_9 = "pti2_9"
    LOC13_5 = "loc13_5"
    SUBURBAN_RAILWAY = "suburbanRailway"
    PTI2_10 = "pti2_10"
    REPLACEMENT_RAIL_SERVICE = "replacementRailService"
    PTI2_11 = "pti2_11"
    SPECIAL_TRAIN_SERVICE = "specialTrainService"
    PTI2_12 = "pti2_12"
    LORRY_TRANSPORT_RAIL_SERVICE = "lorryTransportRailService"
    PTI2_13 = "pti2_13"
    ALL_RAIL_SERVICES = "allRailServices"
    PTI2_14 = "pti2_14"
    CROSS_COUNTRY_RAIL_SERVICE = "crossCountryRailService"
    PTI2_15 = "pti2_15"
    VEHICLE_RAIL_TRANSPORT_SERVICE = "vehicleRailTransportService"
    PTI2_16 = "pti2_16"
    LOC13_8 = "loc13_8"
    RACK_AND_PINION_RAILWAY = "rackAndPinionRailway"
    PTI2_17 = "pti2_17"
    ADDITIONAL_TRAIN_SERVICE = "additionalTrainService"
    PTI2_255 = "pti2_255"
    UNDEFINED = "undefined"
    LOC13_6 = "loc13_6"
    LOCAL = "local"
    LOC13_1 = "loc13_1"
    INTERBATIONAL = "interbational"
