from enum import Enum

__NAMESPACE__ = "http://www.siri.org.uk/siri"


class RoutePointTypeEnumeration(Enum):
    """
    route_point_type TPEG pti_table15.
    """
    PTI15_0 = "pti15_0"
    UNKNOWN = "unknown"
    PTI15_1 = "pti15_1"
    START_POINT = "startPoint"
    PTI15_2 = "pti15_2"
    DESTINATION = "destination"
    PTI15_3 = "pti15_3"
    STOP = "stop"
    PTI15_4 = "pti15_4"
    VIA = "via"
    PTI15_5 = "pti15_5"
    NOT_STOPPING = "notStopping"
    PTI15_6 = "pti15_6"
    TEMPORARY_STOP = "temporaryStop"
    PTI15_7 = "pti15_7"
    TEMPORARILY_NOT_STOPPING = "temporarilyNotStopping"
    PTI15_8 = "pti15_8"
    EXCEPTIONAL_STOP = "exceptionalStop"
    PTI15_9 = "pti15_9"
    ADDITIONAL_STOP = "additionalStop"
    PTI15_10 = "pti15_10"
    REQUEST_STOP = "requestStop"
    PTI15_11 = "pti15_11"
    FRONT_TRAIN_DESTINATION = "frontTrainDestination"
    PTI15_12 = "pti15_12"
    REAR_TRAIN_DESTINATION = "rearTrainDestination"
    PTI15_13 = "pti15_13"
    THROUGH_SERVICE_DESTINATION = "throughServiceDestination"
    PTI15_14 = "pti15_14"
    NOT_VIA = "notVia"
    PTI15_15 = "pti15_15"
    ALTERED_START_POINT = "alteredStartPoint"
    PTI15_16 = "pti15_16"
    ALTERED_DESTINATION = "alteredDestination"
    PTI15_255 = "pti15_255"
    UNDEFINED_ROUTE_POINT = "undefinedRoutePoint"
