from enum import Enum

__NAMESPACE__ = "http://www.siri.org.uk/siri"


class WaterSubmodesOfTransportEnumeration(Enum):
    """
    Values for Water ModesOfTransport: TPEG pti_table_07.
    """
    PTI7_0 = "pti7_0"
    UNKNOWN = "unknown"
    PTI7_1 = "pti7_1"
    INTERNATIONAL_CAR_FERRY_SERVICE = "internationalCarFerryService"
    PTI7_2 = "pti7_2"
    NATIONAL_CAR_FERRY_SERVICE = "nationalCarFerryService"
    PTI7_3 = "pti7_3"
    REGIONAL_CAR_FERRY_SERVICE = "regionalCarFerryService"
    PTI7_4 = "pti7_4"
    LOCAL_CAR_FERRY_SERVICE = "localCarFerryService"
    PTI7_5 = "pti7_5"
    INTERNATIONAL_PASSENGER_FERRY = "internationalPassengerFerry"
    PTI7_6 = "pti7_6"
    NATIONAL_PASSENGER_FERRY = "nationalPassengerFerry"
    PTI7_7 = "pti7_7"
    REGIONAL_PASSENGER_FERRY = "regionalPassengerFerry"
    PTI7_8 = "pti7_8"
    LOCAL_PASSENGER_FERRY = "localPassengerFerry"
    PTI7_9 = "pti7_9"
    POST_BOAT = "postBoat"
    PTI7_10 = "pti7_10"
    TRAIN_FERRY = "trainFerry"
    PTI7_11 = "pti7_11"
    ROAD_FERRY_LINK = "roadFerryLink"
    PTI7_12 = "pti7_12"
    AIRPORT_BOAT_LINK = "airportBoatLink"
    PTI7_13 = "pti7_13"
    HIGH_SPEED_VEHICLE_SERVICE = "highSpeedVehicleService"
    PTI7_14 = "pti7_14"
    HIGH_SPEED_PASSENGER_SERVICE = "highSpeedPassengerService"
    PTI7_15 = "pti7_15"
    SIGHTSEEING_SERVICE = "sightseeingService"
    PTI7_16 = "pti7_16"
    SCHOOL_BOAT = "schoolBoat"
    PTI7_17 = "pti7_17"
    CABLE_FERRY = "cableFerry"
    PTI7_18 = "pti7_18"
    RIVER_BUS = "riverBus"
    PTI7_19 = "pti7_19"
    SCHEDULED_FERRY = "scheduledFerry"
    PTI7_20 = "pti7_20"
    SHUTTLE_FERRY_SERVICE = "shuttleFerryService"
    PTI7_21 = "pti7_21"
    ALL_WATER_TRANSPORT_SERVICES = "allWaterTransportServices"
    PTI7_255 = "pti7_255"
    UNDEFINED_WATER_TRANSPORT = "undefinedWaterTransport"
