from enum import Enum

__NAMESPACE__ = "http://nova.voev.ch/services/v14/vertrieb"


class LeistungsStatus(Enum):
    """
    Der Leistungsstatus ist eine Enum und kann die Werte OFFERIERT,VERKAUFT,
    PRODUKTION_BEREIT, PRODUKTION_ERFOLGREICH, TECHNISCH_STORNIERT und
    NICHT_VERKAUFT annehmen.
    """
    OFFERIERT = "OFFERIERT"
    VERKAUFT = "VERKAUFT"
    PRODUKTION_BEREIT = "PRODUKTION_BEREIT"
    PRODUKTION_ERFOLGREICH = "PRODUKTION_ERFOLGREICH"
    TECHNISCH_STORNIERT = "TECHNISCH_STORNIERT"
    NICHT_VERKAUFT = "NICHT_VERKAUFT"
