from enum import Enum

__NAMESPACE__ = "http://nova.voev.ch/services/v14/vertriebsbase"


class NachweisKategorie(Enum):
    REISENDE_MIT_BEHINDERUNG = "REISENDE_MIT_BEHINDERUNG"
    GA_PLUS_KIND_6_BIS16 = "GA_PLUS_KIND_6BIS16"
    GA_PLUS_JUG_16_BIS25 = "GA_PLUS_JUG_16BIS25"
    GA_PLUS_DUO_FAMILIA_PARTNER = "GA_PLUS_DUO_FAMILIA_PARTNER"
    STUDENTENAUSWEIS = "STUDENTENAUSWEIS"
