from enum import Enum

__NAMESPACE__ = "http://nova.voev.ch/services/v14/geschaeftspartner"


class QualitaetsEigenschaft(Enum):
    KUBA_GEPRUEFT = "KUBA_GEPRUEFT"
    QUALITAET_SITZ_ADRESSE = "QUALITAET_SITZ_ADRESSE"
    QUALITAET_NAME = "QUALITAET_NAME"
    QUALITAET_FESTNETZ = "QUALITAET_FESTNETZ"
    QUALITAET_MOBILE = "QUALITAET_MOBILE"
    QUALITAET_EMAIL = "QUALITAET_EMAIL"
    QUALITAET_GEBURTSDATUM = "QUALITAET_GEBURTSDATUM"
