from enum import Enum

__NAMESPACE__ = "http://nova.voev.ch/services/v14/geschaeftspartner"


class QualitaetsWert(Enum):
    """@Deprecated will be removed in NOVA 15."""
    GEPRUEFT = "GEPRUEFT"
    FORCIERT = "FORCIERT"
    CH_REGISTER_GEPRUEFT = "CH_REGISTER_GEPRUEFT"
    REGEX_GEPRUEFT = "REGEX_GEPRUEFT"
    DOUBLETTE_GEPRUEFT = "DOUBLETTE_GEPRUEFT"
    FORMAL_GEPRUEFT = "FORMAL_GEPRUEFT"
    GEGEN_AUSWEIS_GEPRUEFT = "GEGEN_AUSWEIS_GEPRUEFT"
    ZWEI_FAKTOR_AKTIVIERT = "ZWEI_FAKTOR_AKTIVIERT"
    EMPFANG_GEPRUEFT = "EMPFANG_GEPRUEFT"
    ADRESSE_UNGUELTIG = "ADRESSE_UNGUELTIG"
