from enum import Enum

__NAMESPACE__ = "http://nova.voev.ch/services/v14/vertrieb"


class ReservationsPflicht(Enum):
    PLATZRESERVATION_OBLIGATORISCH = "PLATZRESERVATION_OBLIGATORISCH"
    PLATZRESERVATION_PANORAMA_OBLIGATORISCH = "PLATZRESERVATION_PANORAMA_OBLIGATORISCH"
    VELORESERVATION_OBLIGATORISCH = "VELORESERVATION_OBLIGATORISCH"
