from enum import Enum

__NAMESPACE__ = "http://nova.voev.ch/services/v14/vertrieb"


class SavTyp(Enum):
    ERSTATTUNG = "ERSTATTUNG"
    ANNULLATION = "ANNULLATION"
    ANNULLATION_ERSTATTUNG = "ANNULLATION_ERSTATTUNG"
    HINTERLEGUNG = "HINTERLEGUNG"
    ENTSCHAEDIGUNG = "ENTSCHAEDIGUNG"
    SPERRUNG_NUTZUNG = "SPERRUNG_NUTZUNG"
    SPERRUNG_ERSTATTUNG = "SPERRUNG_ERSTATTUNG"
    ENTSPERRUNG_NUTZUNG = "ENTSPERRUNG_NUTZUNG"
    ENTSPERRUNG_ERSTATTUNG = "ENTSPERRUNG_ERSTATTUNG"
