from enum import Enum

__NAMESPACE__ = "http://nova.voev.ch/services/v14/vertriebsbase"


class VerkaufsAblauf(Enum):
    STRECKENEINSTIEG = "STRECKENEINSTIEG"
    PRODUKTEINSTIEG = "PRODUKTEINSTIEG"
    ZONENEINSTIEG = "ZONENEINSTIEG"
    STRECKENWECHSELEINSTIEG = "STRECKENWECHSELEINSTIEG"
    AKTIVIERUNGSEINSTIEG = "AKTIVIERUNGSEINSTIEG"
    ERSTATTUNGSEINSTIEG = "ERSTATTUNGSEINSTIEG"
