from enum import Enum

__NAMESPACE__ = "http://datex2.eu/schema/2_0RC1/2_0"


class CountryEnum(Enum):
    AT = "at"
    BE = "be"
    BG = "bg"
    CH = "ch"
    CS = "cs"
    CY = "cy"
    CZ = "cz"
    DE = "de"
    DK = "dk"
    EE = "ee"
    ES = "es"
    FI = "fi"
    FO = "fo"
    FR = "fr"
    GB = "gb"
    GG = "gg"
    GI = "gi"
    GR = "gr"
    HR = "hr"
    HU = "hu"
    IE = "ie"
    IM = "im"
    IS = "is"
    IT = "it"
    JE = "je"
    LI = "li"
    LT = "lt"
    LU = "lu"
    LV = "lv"
    MA = "ma"
    MC = "mc"
    MK = "mk"
    MT = "mt"
    NL = "nl"
    NO = "no"
    PL = "pl"
    PT = "pt"
    RO = "ro"
    SE = "se"
    SI = "si"
    SK = "sk"
    SM = "sm"
    TR = "tr"
    VA = "va"
    OTHER = "other"
